[SQL 첫걸음] 3강 ~ 8강 정리
woowacourse-study/2023-gb-code pull request #27
Opened 2023-04-23 04:44 UTC by somsom13

2023-04-24 11:45 UTC, JJ503 requested changes
이미지 첨부까지 완벽하네요! 👍
수정 후 리뷰 재요청 부탁드립니다 ☺️

2023-04-24 11:45 UTC, JJ503 commented on somsom13/SQL_첫걸음/2장_테이블에서_데이터_검색/04_Hello_World_실행하기.md
> +        - 왼쪽 정렬로 표시 (ex. 조이__, 제이미_)
참 좋은 예시네요! 👍

2023-04-24 11:45 UTC, JJ503 commented on somsom13/SQL_첫걸음/2장_테이블에서_데이터_검색/06_검색_조건_지정하기.md
> +- 조건식 `WHERE name = '잼민정수'`  (❤️)
바린이라고 알고 있는데 오타인가요? 🤔

2023-04-24 11:45 UTC, JJ503 commented on somsom13/SQL_첫걸음/2장_테이블에서_데이터_검색/06_검색_조건_지정하기.md
> +- `>` 연산자
인용으로 바뀌어서 그렇다면 아래처럼 수정할 수 있습니다.

```suggestion
- \> 연산자
```

2023-04-24 11:45 UTC, JJ503 commented on somsom13/SQL_첫걸음/2장_테이블에서_데이터_검색/08_패턴_매칭에_의한_검색.md
> +    - `**%` 메타문자는 빈 문자열과도 매치한다!!!**
`**` 이 잘못 들어가 강조 표시가 안 되는 것 같아 확인 부탁합니다~

2023-04-25 12:09 UTC, yeonkkk approved these changes
적절한 예시가 인상 깊었습니다.. 역시 고수;;😉

2023-04-25 12:09 UTC, yeonkkk commented on somsom13/SQL_첫걸음/2장_테이블에서_데이터_검색/04_Hello_World_실행하기.md
> +        - 왼쪽 정렬로 표시 (ex. 조이__, 제이미_)
예시가 귀엽네요 😎

2023-04-25 12:09 UTC, yeonkkk commented on somsom13/SQL_첫걸음/2장_테이블에서_데이터_검색/04_Hello_World_실행하기.md
> +- 셀의 데이터가 NULL로 표시되는 경우: → 아무 것도 저장되어 있지 않음을 의미
`:` 랑 `->` 중에 하나만 사용해도 좋을 것 같아요😀

2023-04-25 12:09 UTC, yeonkkk commented on somsom13/SQL_첫걸음/2장_테이블에서_데이터_검색/06_검색_조건_지정하기.md
> +- 조건식 `WHERE name = '잼민정수'`  (❤️)
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
둘 다 맞는 표현 아닌가요?🤔

2023-04-25 12:09 UTC, yeonkkk commented on somsom13/SQL_첫걸음/2장_테이블에서_데이터_검색/08_패턴_매칭에_의한_검색.md
> +    - text의 값이 “SQL어쩌구저쩌구” 인 필드를 모두 조회한다.
예시가 멋지고, 바론이 적합해요

2023-04-25 12:09 UTC, yeonkkk commented on somsom13/SQL_첫걸음/2장_테이블에서_데이터_검색/08_패턴_매칭에_의한_검색.md
> +    - `WHERE text LIKE '%\%%`
```suggestion
    - `WHERE text LIKE %\%%`
```
이 걸 의도한 걸까요?!🙂

2023-04-30 06:59 UTC, somsom13 commented on somsom13/SQL_첫걸음/2장_테이블에서_데이터_검색/08_패턴_매칭에_의한_검색.md
> +    - `WHERE text LIKE '%\%%`
NO,,,, 저의 실수입니다 감사합니닷

2023-04-30 14:51 UTC, JJ503 approved these changes

2023-04-30 14:51 UTC, merged